# this file is for testing code quality of pull requests
# right now it is just doing simple linting 
# I will add tests for the spark-ai-frontend as well as website

name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.10.4-buster

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.2

      - name: Install Dependencies
        run: make install && make install-pre-commit
        working-directory: ./website

      - name: Lint
        run: make lint
        working-directory: ./website
